### ISSUE TITLE
无法编译

### ISSUE THREAD

**Issue by kongjunZhang** [Aloft-Lab/CTeX-Installer#1]
系统及版本：win 10   ctex:CTeX 3.0.202.0 (alpha)  64位版

Command Line:   pdflatex.exe --interaction=errorstopmode --synctex=-1 "FRBmain.tex"
Startup Folder: C:\Users\zhang\Desktop\kjzhang20220713

pdflatex: security risk: running with elevated privileges
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (MiKTeX 22.12) (preloaded format=pdflatex.fmt)
 restricted \write18 enabled.
entering extended mode
(FRBmain.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2022-12-17> (aastex631.cls
Document Class: aastex631 2020/12/20 Version 6.3.1d/AAS markup document class

 Please update your system to include revtex4-1.cls

 ) )
(\end occurred when \ifx on line 31 was incomplete)
No pages of output.
Transcript written on FRBmain.log.

_____________________________________________________________________

 PDFTeXify Compilation Report (Pages: 0)

 Errors: 0   Warnings: 0   Bad Boxes: 0

**Comment by wulingyun** [comment]
你使用的 aastex631 文档类需要 revtex 宏包的支持。这两个宏包默认都没有安装，请使用开始菜单中的 MiKTeX-Console 的宏包管理功能安装 aastex 宏包和 revtex 宏包后再编译。
