### ISSUE TITLE
 LaTeX Error: Option clash for package CJK.

### ISSUE THREAD

**Issue by MissyDad** [Aloft-Lab/CTeX-Installer#10]
之前的毕业论文（用18年左右的Ctex通过），现在编译不了了。。。

! LaTeX Error: Option clash for package CJK.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.35 \RequirePackageWithOptions
                               {fontenc}
?

**Comment by MissyDad** [comment]
[JNUMasterThesis.zip](https://github.com/Aloft-Lab/CTeX-Installer/files/12077333/JNUMasterThesis.zip)
附件是主文档。

**Comment by wulingyun** [comment]
看了一下你的文档，CJK 宏包和 ctexcap 宏包重复使用了，把 \usepackage{CJK} 一行去掉就好了。
