### ISSUE TITLE
pdflatex编译后中文全部为乱码

### ISSUE THREAD

**Issue by humewang** [Aloft-Lab/CTeX-Installer#11]
版本：CTeX 3.0.216.3
missing character: there is no ?in font gbksong28!
missing character: there is no ！in font gbksong26!
missing character: there is no L in font gbksong34!
missing character: there is no ^^M in font gbksong26!

但更古怪的是，我原来在CTEX2.9上建立的中文beamer文档可在新版ctex中正常通过pdflatex编译。如在新版ctex中新建一个tex文档，即使把老文档的代码全部复制过来，编译后，中文全部为乱码，依然出现以上错误。

请指教，这是怎么呢，太古怪了，哈哈哈

**Comment by wulingyun** [comment]
文件编码的问题，你的老文件应该是 gbk 编码的，所以可以正常编译。而新建的文件，可能保存为 utf8 编码了，所以出现编译错误。用支持编码转换的编辑器打开看看就知道了。

**Comment by humewang** [comment]
> 文件编码的问题，你的老文件应该是 gbk 编码的，所以可以正常编译。而新建的文件，可能保存为 utf8 编码了，所以出现编译错误。用支持编码转换的编辑器打开看看就知道了。

非常感谢解惑！请问这种情况应该怎么处理呢？就是如何把新建tex文档默认设置为使用gbk编码。我用的就是ctex内置的winedt编辑器。每次把老文件另存也不是长久之计啊。

**Comment by wulingyun** [comment]
WinEdt 可以选择菜单 Options --> Preferences ，然后在打开的选项卡中选 Unicode ，把 Enable UTF-8 下方输入框中的 *; 移动到 Enable ANSI 下方的输入框中，如图所示。然后确认即可。
<img width="379" alt="截屏2024-02-24 12 35 42" src="https://github.com/Aloft-Lab/CTeX-Installer/assets/11586350/12807df2-acd8-4b66-8dbd-5a7ca811b8e2">

还是建议把老文件都改为UTF-8编码，这个更方便些，也是长远的趋势。
