### ISSUE TITLE
安装3.0.215,2版本时出现如图所示的弹窗，该怎么破

### ISSUE THREAD

**Issue by TutorHolt251** [Aloft-Lab/CTeX-Installer#12]
![image-20240320105034069](https://github.com/Aloft-Lab/CTeX-Installer/assets/138415414/a0bea951-b287-42d5-8913-7d7cf27e3fa7)

**Comment by wulingyun** [comment]
这个是安装完以后更新MiKTeX时出的错，应该不影响使用。可能和网络等因素有关，可以等以后再找时间更新。

**Comment by TutorHolt251** [comment]
w安分感谢！
