### ISSUE TITLE
安装出现这个怎么破？WinEdt无法弹出pdf窗口

### ISSUE THREAD

**Issue by tangpf135** [Aloft-Lab/CTeX-Installer#13]
![Screenshot 2024-03-21 145154](https://github.com/Aloft-Lab/CTeX-Installer/assets/58031658/f3b3e26e-54be-4d89-94fb-b9d661a62d57)

**Comment by wulingyun** [comment]
这是因为CCT（古老的中文LaTeX扩展）不支持路径中存在空格，因此不能安装在“Program Files”目录下。

即使不使用CCT，也不建议安装在带空格的目录下，建议使用默认的安装目录以避免各种未知问题。

请卸载后重新安装，或者将整个CTEX目录移动到根目录下再运行目录下的Repair.exe程序修复。

**Comment by tangpf135** [comment]
谢谢！已解决

> 这是因为CCT（古老的中文LaTeX扩展）不支持路径中存在空格，因此不能安装在“Program Files”目录下。
> 
> 即使不使用CCT，也不建议安装在带空格的目录下，建议使用默认的安装目录以避免各种未知问题。
> 
> 请卸载后重新安装，或者将整个CTEX目录移动到根目录下再运行目录下的Repair.exe程序修复。
