### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by ipsmile** [Aloft-Lab/CTeX-Installer#2]
请问在 Ubuntu 20.04 如何装设 cTeX packages? 正常装设指令：
tlmgr install ctex
但是下载档案中没有 ctex.cls or ctex.sty 
感谢指引。

**Comment by note286** [comment]
你问错地方了吧，你说的是ctex宏集吧，是[CTeX-org/ctex-kit: Macro Packages and Scripts for Chinese TeX users](https://github.com/CTeX-org/ctex-kit)。

当前仓库是CTeX套装，只有Windows版本的，没有Ubuntu版本。

你用`tlmgr`管理包，你应该使用的是TeX Live吧，如果使用TeX Live，ctex宏集已经内置了。
