### ISSUE TITLE
求助! ctex使用时，整个电脑开始不断刷新,卡顿,如何解决?

### ISSUE THREAD

**Issue by tanflight** [Aloft-Lab/CTeX-Installer#3]
求助! ctex使用时，整个电脑开始不断刷新,卡顿,如何解决?
刷新一段时间后又会回复正常

**Comment by wulingyun** [comment]
是什么版本的ctex？可能是在下载更新package。

**Comment by tanflight** [comment]
是最新的稳定版 CTeX 2.9.2.167。
是使用期间会不定时的出现这种故障

**Comment by wulingyun** [comment]
刷新是指什么，屏幕在闪？编译过程有报错吗？能正确生成PDF文件吗？

2.9.2 只是重新编译了一下安装程序以解决原来存在的bug，其中的内容都还是10年前的，各组件程序都可能和新的操作系统有兼容性问题。

特别是 MiKTeX 已经无法在线更新和安装package 了，如果是为了兼容老文件或者其他原因非要装 2.9.2 ，建议安装 Full 版本。

否则还是建议安装 3.0 ，没啥问题。

**Comment by tanflight** [comment]
感谢，安装3.0 beta版后没问题了
