### ISSUE TITLE
CTeX_3.0.212.1_x64，编译后无法弹出PDF

### ISSUE THREAD

**Issue by Heesophia** [Aloft-Lab/CTeX-Installer#4]
求助

**Comment by wulingyun** [comment]
提问时请提供具体一点的信息。

是用 WinEdt 吗？WinEdt 的默认设置只有部分编译方式可以自动弹出PDF Preview，例如 PDFTeXify。可以自己配置一下：打开主菜单 Options --> Execution Modes ... 找到你使用的编译方式，在右侧的列表中选中“Start Viewer“，点击OK保存。

如下图所示。

<img width="611" alt="截屏2023-03-06 20 48 37" src="https://user-images.githubusercontent.com/11586350/223115435-c440a3a9-26e4-41d2-941c-f54f32d44a31.png">

**Comment by Heesophia** [comment]
问题解决了，谢谢你~
