### ISSUE TITLE
安装212.1版本时，报错如图所示

### ISSUE THREAD

**Issue by ComDou** [Aloft-Lab/CTeX-Installer#5]
![图片1](https://user-images.githubusercontent.com/118092351/225796687-7be13c9b-4dfc-4ae2-9f9f-ae3d6f1cceac.jpg)

**Comment by wulingyun** [comment]
建议不要安装到带空格的目录里，一些古老的程序不支持。

如果不使用CCT可以忽略这个错误，应该不影响其他程序的使用。

**Comment by ComDou** [comment]
好的，谢谢
