### ISSUE TITLE
ctex版本切换后报错

### ISSUE THREAD

**Issue by 1021149914** [Aloft-Lab/CTeX-Installer#6]
从2.9切换到3.0后，好像由于latex版本和编码问题导致下面的报错

`! Use of \??? doesn't match its definition.
<argument> \???
                 ! LaTeX Error: Charcode requested out of engine range.
l.1 \begin{abstract}

?
! Use of \??? doesn't match its definition.
<argument> \???
                 ! LaTeX Error: Access to an entry beyond an array's bounds.
l.1 \begin{abstract}

?
! Use of \??? doesn't match its definition.
<argument> \???
                 ! LaTeX Error: Access to an entry beyond an array's bounds.
l.1 \begin{abstract}

?
! Improper alphabetic constant.
<to be read again>
                   \CTEX@char@nnn@n
l.1 \begin{abstract}`

想请问一下，有什么解决办法嘛

**Comment by 1021149914** [comment]
看报错的意思，charcode（编码格式？）超过engine range？不太理解为什么。
用记事本打开tex文件后，右下角编码格式好像是windows（CRLF） ANSI

**Comment by 1021149914** [comment]
好像是因为3.0删除了CASthesis，但是我这边的是基于CASthesis上修改的

**Comment by wulingyun** [comment]
应该不是CASthesis宏包的问题，如果缺少cls文件会直接报错的。估计还是文件的编码，改为UTF8试试？

**Comment by 1021149914** [comment]
改了编码，换了新错误
` [6] (../chapter/abstract-ch.tex
Missing character: There is no � in font txb!

! LaTeX Error: Invalid UTF-8 byte "F9.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.1 \begin{abstract}

? H
The document does not appear to be in UTF-8 encoding.
Try adding \UseRawInputEncoding as the first line of the file
or specify an encoding such as \usepackage [latin1]{inputenc}
in the document preamble.
Alternatively, save the file in UTF-8 using your editor or another tool`

感觉应该是MiKTeX中一些包过新导致的。但是报错信息就很奇怪，事实情况确实已经全换成utf8了。

**Comment by wulingyun** [comment]
The document does not appear to be in UTF-8 encoding.

感觉还是编码的问题，再检查一下所有文件的编码，以及有没有异常字符
