### ISSUE TITLE
将 tabu 替换为 tabularray？

### ISSUE THREAD

**Issue by lvjr** [Aloft-Lab/CTeX-Installer#7]
在 `required_packages.txt` 里包含的 `tabu` 宏包多年未更新，现在和 latex 内核以及其他宏包冲突，基本处于不可用状态（见[这里](https://github.com/tabu-issues-for-future-maintainer/tabu)）。是否可以将 `tabu` 替换为我编写的替代宏包 [tabularray](https://ctan.org/pkg/tabularray)？

**Comment by wulingyun** [comment]
好的，下次更新时会加入。谢谢！
