### ISSUE TITLE
.exe文件无法被信任

### ISSUE THREAD

**Issue by JatifoneYan** [Aloft-Lab/CTeX-Installer#9]
在Edge浏览器里下载.exe文件后，显示需要确认信任，无法运行起来
![微信图片_20230512190327](https://github.com/Aloft-Lab/CTeX-Installer/assets/130362584/11a49b03-9804-4b7f-b2b9-329ab249df1d)

**Comment by wulingyun** [comment]
这是 Edge 浏览器的安全提示，下载任何 exe 文件都会如此。
点击右侧的 ... 在打开的菜单中选择“保留”即可。

**Comment by wulingyun** [comment]
参见以下截图：
<img width="328" alt="截屏2023-05-12 22 17 26" src="https://github.com/Aloft-Lab/CTeX-Installer/assets/11586350/c7891896-04bf-4759-975a-ebb28bf7f203">
<img width="332" alt="截屏2023-05-12 22 18 06" src="https://github.com/Aloft-Lab/CTeX-Installer/assets/11586350/cb18a445-da88-4a85-9a8e-c93b2192eede">
<img width="336" alt="截屏2023-05-12 22 18 49" src="https://github.com/Aloft-Lab/CTeX-Installer/assets/11586350/d55c7942-52a1-41b2-b4ac-cb28d01f5657">
